# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hUjreAXTXA5fK_Wmngk2TT9fbtWpchJp
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from sklearn.ensemble import RandomForestRegressor

# ==========================
# LOAD DATASET
# ==========================

# Define column names for the Boston Housing dataset as the file usually doesn't have headers
feature_names = ['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT', 'MEDV']

# Load the dataset, assuming it's space-delimited and has no header
df = pd.read_csv("housing.csv", delim_whitespace=True, header=None)
df.columns = feature_names # Assign the column names

print("Dataset Shape:", df.shape)
print(df.head())

# ==========================
# TARGET COLUMN
# ==========================

target_column = "MEDV"

X = df.drop(columns=[target_column])
y = df[target_column]

# ==========================
# NUMERIC FEATURES
# ==========================

numeric_features = X.columns.tolist()

numeric_transformer = Pipeline(
    steps=[
        ("imputer",
         SimpleImputer(strategy="median"))
    ]
)

preprocessor = ColumnTransformer(
    transformers=[
        ("num",
         numeric_transformer,
         numeric_features)
    ]
)

# ==========================
# MODEL
# ==========================

model = Pipeline(
    steps=[
        ("preprocessor",
         preprocessor),

        ("regressor",
         RandomForestRegressor(
             n_estimators=300,
             random_state=42
         ))
    ]
)

# ==========================
# TRAIN TEST SPLIT
# ==========================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

# ==========================
# TRAIN MODEL
# ==========================

model.fit(X_train, y_train)

# ==========================
# PREDICTIONS
# ==========================

y_pred = model.predict(X_test)

# ==========================
# EVALUATION
# ==========================

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("\nMean Absolute Error:", mae)
print("\nMean Squared Error:", mse)
print("\nR2 Score:", r2)

# ==========================
# R2 SCORE VISUALIZATION
# ==========================

plt.figure(figsize=(6,4))

plt.bar(
    ["R2 Score"],
    [r2 * 100],
    color="green"
)

plt.ylabel("Score (%)")
plt.title("Boston House Price Prediction")

plt.text(
    0,
    r2 * 100 + 1,
    f"{r2*100:.2f}%"
)

plt.show()

# ==========================
# ACTUAL VS PREDICTED
# ==========================

plt.figure(figsize=(8,6))

plt.scatter(
    y_test,
    y_pred,
    alpha=0.7
)

plt.xlabel("Actual Prices")
plt.ylabel("Predicted Prices")

plt.title(
    "Actual vs Predicted House Prices"
)

plt.show()

# ==========================
# SAVE PREDICTIONS
# ==========================

results = pd.DataFrame({
    "Actual Price": y_test,
    "Predicted Price": y_pred
})

results.to_csv(
    "house_price_predictions.csv",
    index=False
)

print("\nPredictions saved successfully!")